export const GET_ACTIVE_NOTES_REQUEST = "GET_ACTIVE_NOTES_REQUEST";
export const GET_ACTIVE_NOTES_SUCCESS = "GET_ACTIVE_NOTES_SUCCESS";
export const GET_ACTIVE_NOTES_FAILURE = "GET_ACTIVE_NOTES_FAILURE";

export const GET_ARCHIVED_NOTES_REQUEST = "GET_ARCHIVED_NOTES_REQUEST";
export const GET_ARCHIVED_NOTES_SUCCESS = "GET_ARCHIVED_NOTES_SUCCESS";
export const GET_ARCHIVED_NOTES_FAILURE = "GET_ARCHIVED_NOTES_FAILURE";
