export const GET_NOTES_BY_TYPE_REQUEST = "GET_NOTES_BY_TYPE_REQUEST";
export const GET_NOTES_BY_TYPE_SUCCESS = "GET_NOTES_BY_TYPE_SUCCESS";
export const GET_NOTES_BY_TYPE_FAILURE = "GET_NOTES_BY_TYPE_FAILURE";

export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_FAILURE = "UPDATE_NOTE_FAILURE";

export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAILURE = "DELETE_NOTE_FAILURE";

export const ADD_NOTE_REQUEST = "ADD_NOTE_REQUEST";
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAILURE = "ADD_NOTE_FAILURE";

export const GET_NOTE_BY_ID_REQUEST = "GET_NOTE_BY_ID_REQUEST";
export const GET_NOTE_BY_ID_SUCCESS = "GET_NOTE_BY_ID_SUCCESS";
export const GET_NOTE_BY_ID_FAILURE = "GET_NOTE_BY_ID_FAILURE";

export const GET_NOTES_BY_SEARCH_REQUEST = "GET_NOTES_BY_SEARCH_REQUEST";
export const GET_NOTES_BY_SEARCH_SUCCESS = "GET_NOTES_BY_SEARCH_SUCCESS";
export const GET_NOTES_BY_SEARCH_FAILURE = "GET_NOTES_BY_SEARCH_FAILURE";

export const TOGGLE_DARK_THEME = "TOGGLE_DARK_THEME";
export const CLEAR_NOTES = "CLEAR_NOTES";